### ISSUE TITLE
Swift Error: Variable used within its own initial value

### ISSUE THREAD

**Issue by Javanaise** [maartenschumacher/TicTacToe#2]
line 39 in ViewController.swift

**Comment by maartenschumacher** [comment]
Actually this error has already been solved, I will push an update later today. Then there will be another error though, which anybody is welcome to look at. But as I said in the readme, this is more of a programming experiment than an app which has to go into production at some point, so making it compile is not as important as the ideas behind it :)

**Comment by maartenschumacher** [comment]
Thanks for checking it out though! :)

**Comment by Javanaise** [comment]
Thanks!
